version: '3.0'

services:
  mysql-picture-db:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - /Users/ybzhou/sql-data/picture:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=picture
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
  spring-boot-picture:
    image: felix/picture:latest
    depends_on:
      - mysql-picture-db
    ports:
      - 8081:8081
    volumes:
      - /tmp:/tmp
    environment:
      - DATABASE_HOST=mysql-picture-db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=picture
