DROP TABLE IF EXISTS images;
CREATE TABLE `images` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  `name` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;